

[pytest]
addopts = -v -s
testpaths = Tests

markers =
     api: API test cases
     ui: UI test cases
     integration: API + UI integration tests
     smoke: critical smoke tests
     regression: full regression suite

